FROM apache/airflow:2.10.0

USER airflow
FROM apache/airflow:2.10.0

USER airflow

RUN pip install --no-cache-dir \
    yfinance \
    pandas \
    psycopg2-binary \
    python-dotenv \
    neo4j \
    pydantic \
    pydantic-settings