services:

  postgres:
    image: postgres:17
    container_name: intel-ai-postgres

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

  neo4j:
    image: neo4j:5
    container_name: intel-ai-neo4j

    environment:
      NEO4J_AUTH: ${NEO4J_USERNAME}/${NEO4J_PASSWORD}

    ports:
      - "7474:7474"
      - "7687:7687"

    volumes:
      - neo4j_data:/data

    restart: unless-stopped

  airflow:
    build:
      context: .
      dockerfile: Dockerfile.airflow

    container_name: intel-ai-airflow

    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"

    ports:
      - "8080:8080"

    command: standalone

    volumes:
      - ./services/etl-service:/opt/airflow/etl-service
      - ./services/etl-service/app/dags:/opt/airflow/dags
      - ./.env.docker:/opt/airflow/.env

    depends_on:
      - postgres

    restart: unless-stopped

  sentiment-worker:
    build:
      context: .
      dockerfile: services/etl-service/Dockerfile

    container_name: intel-ai-sentiment-worker

    env_file:
      - .env.docker

    command: >
      uv run python -m app.jobs.sentiment_worker

    depends_on:
      - postgres

    restart: unless-stopped

  agent:
    build:
      context: .
      dockerfile: services/agent-service/Dockerfile

    container_name: intel-ai-agent

    ports:
      - "8000:8000"

    env_file:
      - .env.docker

    depends_on:
      - postgres
      - neo4j

    restart: unless-stopped

  research:
    build:
      context: .
      dockerfile: services/research-service/Dockerfile

    container_name: intel-ai-research

    ports:
      - "8001:8001"

    env_file:
      - .env.docker

    depends_on:
      - postgres
      - neo4j

    restart: unless-stopped

  news:
    build:
      context: .
      dockerfile: services/news-service/Dockerfile

    container_name: intel-ai-news

    ports:
      - "8002:8002"

    env_file:
      - .env.docker

    depends_on:
      - postgres
      - neo4j

    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: intel-ai-frontend

    ports:
      - "3000:3000"

    environment:
      NEXT_PUBLIC_AGENT_API: http://localhost:8000

    depends_on:
      - agent

    restart: unless-stopped

volumes:
  postgres_data:
  neo4j_data: