"""
LangGraph State.

Defines the shared state
used throughout the
LangGraph workflow.
"""

from typing import Any, TypedDict


class AgentState(TypedDict):
    """
    Shared workflow state.

    Every workflow node
    can read and update
    this state.

    Attributes
    ----------
    question : str
        Original user question.

    route : dict[str, Any] | None
        Routing information
        generated by the
        Supervisor Agent.

    agent_response : Any | None
        Structured response
        returned by the
        selected domain agent.

    final_response : str | None
        Final natural language
        response generated
        for the user.
    """

    # Original user question
    question: str

    # Supervisor routing decision
    route: dict[str, Any] | None

    # Response returned by the selected agent
    agent_response: Any | None

    # Final LLM-generated response
    final_response: str | None