"""
Database models for the Financial Research Agent.

This module defines all PostgreSQL tables used by the application:
- Companies
- Stock Prices
- News Metadata
- Sentiment Scores
- Research Scores
- Risk Scores
"""

from datetime import datetime

from sqlalchemy import (
    BigInteger,
    Boolean,
    Column,
    Date,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
)
from sqlalchemy.orm import DeclarativeBase


class Base(DeclarativeBase):
    """
    Base class for all SQLAlchemy ORM models.
    """

    pass


class Company(Base):
    """
    Stores company master data.

    Attributes:
        id: Unique company identifier.
        company_name: Full company name.
        ticker: Stock market ticker symbol.
        sector: Business sector classification.
    """

    __tablename__ = "companies"

    id = Column(Integer, primary_key=True)

    company_name = Column(String, nullable=False)

    ticker = Column(String, nullable=False)

    sector = Column(String, nullable=False)


class StockPrice(Base):
    """
    Stores daily stock price information.

    Attributes:
        id: Unique stock price record identifier.
        company_id: Reference to company.
        trade_date: Trading date.
        open_price: Opening price.
        high_price: Highest price of the day.
        low_price: Lowest price of the day.
        close_price: Closing price.
        volume: Trading volume.
    """

    __tablename__ = "stock_prices"

    id = Column(Integer, primary_key=True)

    company_id = Column(
        Integer,
        ForeignKey("companies.id")
    )

    trade_date = Column(Date)

    open_price = Column(Float)

    high_price = Column(Float)

    low_price = Column(Float)

    close_price = Column(Float)

    volume = Column(BigInteger)


class NewsMetadata(Base):
    """
    Stores news article metadata.

    Attributes:
        id: Unique news record identifier.
        company_id: Reference to company.
        title: News headline.
        source: News source or publisher.
        url: Article URL.
        published_date: Publication timestamp.
        is_processed: Whether sentiment analysis has been completed.
    """

    __tablename__ = "news_metadata"

    id = Column(
        Integer,
        primary_key=True
    )

    company_id = Column(
        Integer,
        ForeignKey("companies.id")
    )

    title = Column(Text)

    source = Column(String)

    url = Column(Text)

    published_date = Column(DateTime)

    is_processed = Column(
        Boolean,
        default=False
    )


class SentimentScore(Base):
    """
    Stores sentiment scores generated from news analysis.

    Attributes:
        id: Unique sentiment record identifier.
        news_id: Reference to news article.
        company_id: Reference to company.
        sentiment_score: Numeric sentiment score.
        sentiment_label: positive, neutral or negative.
        confidence_score: FinBERT confidence score.
        created_at: Record creation timestamp.
    """

    __tablename__ = "sentiment_scores"

    id = Column(
        Integer,
        primary_key=True
    )

    news_id = Column(
        Integer,
        ForeignKey("news_metadata.id"),
        unique=True,
        nullable=False
    )

    company_id = Column(
        Integer,
        ForeignKey("companies.id"),
        nullable=False
    )

    sentiment_score = Column(
        Float,
        nullable=False
    )

    sentiment_label = Column(
        String,
        nullable=False
    )

    confidence_score = Column(
        Float,
        nullable=False
    )

    created_at = Column(
        DateTime,
        default=datetime.utcnow
    )


class ResearchScore(Base):
    """
    Stores research scores generated by the research agent.

    Attributes:
        id: Unique research score identifier.
        company_id: Reference to company.
        research_score: Calculated research score.
        created_at: Record creation timestamp.
    """

    __tablename__ = "research_scores"

    id = Column(Integer, primary_key=True, index=True)

    company_id = Column(
        Integer,
        ForeignKey("companies.id")
    )

    research_score = Column(Float)

    created_at = Column(
        DateTime,
        default=datetime.utcnow
    )


class RiskScore(Base):
    """
    Stores risk scores generated for companies.

    Attributes:
        id: Unique risk score identifier.
        company_id: Reference to company.
        risk_score: Calculated risk score.
        created_at: Record creation timestamp.
    """

    __tablename__ = "risk_scores"

    id = Column(Integer, primary_key=True, index=True)

    company_id = Column(
        Integer,
        ForeignKey("companies.id")
    )

    risk_score = Column(Float)

    created_at = Column(
        DateTime,
        default=datetime.utcnow
    )
class ResearchReport(Base):
    """
    Stores metadata about annual and quarterly reports.
    """

    __tablename__ = "research_reports"

    id = Column(
        Integer,
        primary_key=True
    )

    company_id = Column(
        Integer,
        ForeignKey("companies.id"),
        nullable=False
    )

    report_type = Column(
        String,
        nullable=False
    )

    year = Column(
        Integer,
        nullable=False
    )

    quarter = Column(
        String,
        nullable=True
    )

    pdf_path = Column(
        Text,
        nullable=False
    )

    created_at = Column(
        DateTime,
        default=datetime.utcnow
    )
class DocumentChunk(Base):
    """
    Stores report chunks.
    """

    __tablename__ = "document_chunks"

    id = Column(
        Integer,
        primary_key=True
    )

    report_id = Column(
        Integer,
        ForeignKey("research_reports.id"),
        nullable=False
    )

    chunk_number = Column(
        Integer,
        nullable=False
    )

    chunk_text = Column(
        Text,
        nullable=False
    )

    created_at = Column(
        DateTime,
        default=datetime.utcnow
    )