"""
Agent Routes.

Provides REST APIs
for the Trading
Research Agent.
"""

from fastapi import (
    APIRouter,
    HTTPException
)

from app.schemas.chat import (
    ChatRequest,
    ChatResponse
)

from app.services.chat_service import (
    ask_question
)


router = APIRouter(

    tags=["Agent"]

)


# ---------------------------------------------------------
# Ask Question
# ---------------------------------------------------------

@router.post(

    "/ask",

    response_model=ChatResponse

)
def ask(
    request: ChatRequest
):
    """
    Process a user
    research question.

    Parameters
    ----------
    request : ChatRequest

    Returns
    -------
    ChatResponse
        Final AI response
        generated by the
        LangGraph workflow.
    """

    try:

        answer = ask_question(

            request.question

        )

        return ChatResponse(

            answer=answer

        )

    except Exception as error:

        raise HTTPException(

            status_code=500,

            detail=str(error)

        )


# ---------------------------------------------------------
# Health Check
# ---------------------------------------------------------

@router.get(

    "/health"

)
def health_check():
    """
    Agent Service
    health check.

    Returns
    -------
    dict
    """

    return {

        "service": "Agent Service",

        "status": "Running"

    }